- name: Find eth node
  set_fact:
    eth_node_ip: "{% set eth_ips = [] %}{% for item in groups['role_eth'] %}{% do eth_ips.append(hostvars[item]['private_ip']) %}{% endfor %}{{ eth_ips[private_ip | ipaddr('int') % eth_ips|length] }}"

- debug:
    var: eth_node_ip

- name: Ensure Raiden node log-dir
  become: yes
  file:
    name: "{{ raiden_node_log_root }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0700

- name: Raiden docker container
  docker_container:
    name: raiden
    state: started
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_raiden }}"
    etc_hosts:
      logstash: "{{ hostvars[groups['role_infrastructure'][0]]['private_ip'] }}"
    hostname: "{{ hostname }}"
    ports:
      - 38647:38647/udp
      - 5001:5001
    volumes:
      - "{{ raiden_root }}:/root/.raiden"
      - "{{ keystore_root }}:/keystore"
      - "{{ raiden_node_log_root }}:/log"
#    env:
#      RAIDEN_LOGSTASH_HOST: logstash
    command:
      - "--gas-price"
      - "fast"
      - "--eth-rpc-endpoint"
      - "http://{{ eth_node_ip }}:8545"
      - "--api-address"
      - "0.0.0.0:5001"
      - "--keystore-path"
      - "/keystore"
      - "--address"
      - "{{ keystore_address }}"
      - "--password-file"
      - "/keystore/password"
      - "--transport"
      - "{{ transport }}"
      - "--log-config"
      - ":info,raiden:debug"
      - "--log-json"
      - "--log-file"
      - "/log/raiden.log"
      - "--accept-disclaimer"
      - "{{ 'echonode' if hostvars[inventory_hostname].get('tags.Echo') == 'true' else '' }}"
      - "{{ '--token-address' if hostvars[inventory_hostname].get('tags.Echo') == 'true' else '' }}"
      - "{{ echo_node_token_address if hostvars[inventory_hostname].get('tags.Echo') == 'true' else '' }}"
